version: "3.8"
services:
  broker:
    image: "go-broker"
    build:
      context: ./
    ports:
      - "50043:50043"
      - "2112:2112"
    environment:
      - GO_BROKER__SERVER__HOST=0.0.0.0:50043
      - GO_BROKER__TRACING__USE_JAEGER=true
      - GO_BROKER__TRACING__JAEGER_AGENT_HOST=jaeger
      - GO_BROKER__TRACING__JAEGER_AGENT_PORT=6831

  metrics:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - broker

  grafana:
    image: grafana/grafana-enterprise:10.0.2
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - metrics

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"

volumes:
  grafana_data:
