{
 "title": "Go Broker Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_subscribers", "legendFormat": "active" }
   ]
  },
  {
   "title": "Method Duration Publish",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "method_duration{method=\"publish\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Method Duration Fetch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "method_duration{method=\"fetch\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Method Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(method_count[$__rate_interval])",
     "legendFormat": "{{method}}-{{success}}"
    }
   ]
  }
 ]
}