apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-broker-broker-dep
spec:
  template:
    metadata:
      name: broker
      labels:
        app: go-broker-broker
    spec:
      containers:
        - name: broker
          image: go-broker
          imagePullPolicy: Never
          ports:
            - containerPort: 50043
            - containerPort: 2112
          env:
            - name: GO_BROKER__SERVER__HOST
              value: "0.0.0.0:50043"
            - name: GO_BROKER__TRACING__USE_JAEGER
              value: "true"
            - name: GO_BROKER__TRACING__JAEGER_AGENT_HOST
              value: "jaeger"
            - name: GO_BROKER__TRACING__JAEGER_AGENT_PORT
              value: "6831"
          envFrom:
            - configMapRef:
                name: broker-configmap
  selector:
    matchLabels:
      app: go-broker-broker
  replicas: 1
