apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: NodePort
  ports:
    - port: 50043
      nodePort: 30043
      name: broker-port
    - port: 9901
      nodePort: 30001
      name: admin-port
  selector:
    app: go-broker-envoy