apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-broker-grafana-dep
spec:
  template:
    metadata:
      name: grafana
      labels:
        app: go-broker-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-enterprise:10.0.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-config
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-dashboards
  selector:
    matchLabels:
      app: go-broker-grafana
  replicas: 1
