apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-broker-jaeger-dep
spec:
  template:
    metadata:
      name: jaeger
      labels:
        app: go-broker-jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 16686
  selector:
    matchLabels:
      app: go-broker-jaeger
  replicas: 1
