apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-broker-postgres-dep
spec:
  template:
    metadata:
      name: postgres
      labels:
        app: go-broker-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          startupProbe:
            initialDelaySeconds: 30
            exec:
              command:
                - pg_isready
          command:
            - postgres
            - -c
            - max_connections=200
  selector:
    matchLabels:
      app: go-broker-postgres
  replicas: 1
